version: '3.3'

services:
 php:
  build:
   context: .
   dockerfile: dockerfile
  container_name: php
  depends_on:
   - db
  image: php:8.1-apache
  volumes:
   - ../public:/var/www/html/
  extra_hosts:
   - "baluchon.docker:127.0.0.1"
  hostname: baluchon.docker
  domainname: docker
  ports:
   - 80:80
 db:
  container_name: mysql
  image: mysql:8.0
  command: --default-authentication-plugin=mysql_native_password
  environment:
   MYSQL_ROOT_PASSWORD: baluchon
   MYSQL_DATABASE: baluchon
   MYSQL_USER: baluchon
   MYSQL_PASSWORD: baluchon
  ports:
   - 3306:3306
 phpmya:
  image: phpmyadmin/phpmyadmin:latest
  container_name: phpmyadmin
  environment:
   PMA_ARBITRARY: 1
   PMA_HOST: db
   PMA_USER: baluchon
   PMA_PASSWORD: baluchon
   UPLOAD_LIMIT: 20M
  ports:
   - 8899:80
